#include 'totvs.ch'
#include 'Protheus.ch'

//@see https://tdn.totvs.com/display/tec/TComboBox
//@see https://tdn.totvs.com/display/tec/TComboBox%3ANew
user function zTComboBox()
	local oDlg
    //                  1       2       3       4           5           6               7                   
    local aOpcao := {"Feliz","Triste","Calmo","Otimista","Bitcoin","Alta infinita","Modelo Stock to Flow"}
	local cOpcao := aOpcao[5]
    local oRadio //variavel que armazenará o Objeto

    oDlg := TDialog():new(0,0,500,700,'Painel de ComboBox',,,,,CLR_BLACK,CLR_WHITE,,,.T.)
    oRadio := TComboBox():New(10,10,{|u|if(PCount()>0,cOpcao:=u,cOpcao)},aOpcao,100,20,oDlg,,{||FWAlertSuccess(cOpcao,'Mudou item da combo')},,,,.T.,,,,,,,,,'cCombo')

    oButton1 := TButton():New(10, 130, "Mostrar Escolha", oDlg,{|| FWAlertSuccess(cOpcao,"Voce selecionou ")}, 60,15,,,.F.,.T.,.F.,,.F.,,,.F. )

	oDlg:Activate(,,,.T.)


RETURN

