#include 'totvs.ch'

//@see https://tdn.totvs.com/display/tec/Construtor+TGet%3ANew
//@see https://tdn.totvs.com/display/public/framework/Space
user function zTGet()
	local oDlg,oButton,oButton2,oButton3,oButton4,oButton5
	local oSay1,oSay2,oSay3,oSay4,oSay5,oSay6
	local oFont,oFont1
	local cGet1 := space(20)
    local cGet2 := space(30)
	local oGet1,oGet2 //recebe a classe
	local aSize := MsAdvSize()

	oDlg := TDialog():New(aSize[7], aSize[1], aSize[6], aSize[5], 'Aprendendo TGet', , , , , CLR_BLACK, CLR_WHITE, , , .T.)

	//oFont  := TFont():New('Courier new',,60,.T.)
	//oFont1 := TFont():New('Courier new',,20,.F.)
	//obs TFont tem que ficar primeiro
	oFont  := TFont():New('Comic Sans MS', , 16, , .T., , , , , .T., .T.)
	oFont1 := TFont():New('Arial Black'  , , 12, , .F., , , , , .F., .F.)

    /*
    1º coordenada vertical
    2º coordenada horizontal
    3º titulo do botão
    4º Elemento onde ele será fixado
    5º Ação executada ao clica no botão ao clicar com o botão esquerdo do mouse
    */                      //1    2     3              4      5
	oButton  := TButton():New(050, 010, "Mostrar Nome"    , oDlg, {||MsgInfo(cGet1,"Nome")}    , 50, 10, , oFont1, .F., .T., .F., , .F., , , .F.)
	oButton2 := TButton():New(050, 080, "Mostrar Endereço", oDlg, {||MsgInfo(cGet2,"Endereço")}, 50, 10, , oFont1, .F., .T., .F., , .F., , , .F.)
	/*oButton3 := TButton():New(060, 050, "Produtos"    , oDlg, {||MATA010()} , 50, 10, ,oFont1, .F., .T., .F., , .F., , , .F.)
	oButton4 := TButton():New(080, 050, "Bancos"      , oDlg, {||MATA070()} , 50, 10, ,oFont1, .F., .T., .F., , .F., , , .F.)
	oButton5 := TButton():New(100, 050, "Fechar"      , oDlg, {||oDlg:End()}, 50, 10, ,oFont1, .F., .T., .F., , .F., , , .F.)
    */
	//objeto := Clase:Metodo
	//                  1   2     3                            4    5 6
	oSay1 := TSay():New(10, 10 , {|| 'NOME' }    , oDlg, , oFont , , , , .T., , , 400, 300, , , , , ,)
	oSay2 := TSay():New(10, 080, {|| 'ENDEREÇO' }, oDlg, , oFont1, , , , .T., , , 400, 300, , , , , ,)
	/*oSay3 := TSay():New(30, 50, {|| 'abir Fornecedores' }    , oDlg, ,oFont1, , , , .T., , , 400, 300, , , , , ,)
	oSay4 := TSay():New(50, 50, {|| 'abir Produtos' }        , oDlg, ,oFont1, , , , .T., , , 400, 300, , , , , ,)
	oSay5 := TSay():New(70, 50, {|| 'abir Bancos' }          , oDlg, ,oFont1, , , , .T., , , 400, 300, , , , , ,)
	oSay6 := TSay():New(90, 50, {|| 'Fechar' }               , oDlg, ,oFont1, , , , .T., , , 400, 300, , , , , ,)
    */


	oGet1 := TGet():New(30, 10 , {|u|iif(PCount()==0,cGet1,cGet1:=u)}, oDlg, 060, 010, "@!", , 0, , , .F., , .T., , .F., , .F., .F., , .F., .F., , cGet1, , , ,)
    oGet2 := TGet():New(30, 080, {|u|iif(PCount()==0,cGet2,cGet2:=u)}, oDlg, 060, 010, "@!", , 0, , , .F., , .T., , .F., , .F., .F., , .F., .F., , cGet2, , , ,)

	oDlg:Activate(,,,.T.)


return
